
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 413, in main
web-1  |     run(
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 580, in run
web-1  |     server.run()
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 67, in run
web-1  |     return asyncio.run(self.serve(sockets=sockets))
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
web-1  |     return runner.run(main)
web-1  |            ^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
web-1  |     return self._loop.run_until_complete(task)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 71, in serve
web-1  |     await self._serve(sockets)
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 78, in _serve
web-1  |     config.load()
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 436, in load
web-1  |     self.loaded_app = import_from_string(self.app)
web-1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
web-1  |     module = importlib.import_module(module_str)
web-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
db-1   | 2025-08-19 06:38:10.194 UTC [48] LOG:  checkpoint starting: shutdown immediate
web-1  |     return _bootstrap._gcd_import(name[level:], package, level)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
web-1  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
web-1  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
web-1  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
web-1  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
web-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
web-1  |   File "/app/app/main.py", line 2, in <module>
web-1  |     from app.api.routes import auth, user
web-1  |   File "/app/app/api/routes/auth.py", line 4, in <module>
web-1  |     from app.db.session import get_db
web-1  |   File "/app/app/db/session.py", line 3, in <module>
web-1  |     from app.core.config import settings
web-1  |   File "/app/app/core/config.py", line 1, in <module>
web-1  |     from pydantic import BaseSettings
web-1  |   File "/usr/local/lib/python3.11/site-packages/pydantic/__init__.py", line 426, in __getattr__
web-1  |     return _getattr_migration(attr_name)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/site-packages/pydantic/_migration.py", line 296, in wrapper
web-1  |     raise PydanticImportError(
web-1  | pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.11/migration/#basesettings-has-moved-to-pydantic-settings for more details.
web-1  |
web-1  | For further information visit https://errors.pydantic.dev/2.11/u/import-error
db-1   | 2025-08-19 06:38:10.780 UTC [48] LOG:  checkpoint complete: wrote 922 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.075 s, sync=0.433 s, total=0.611 s; sync files=301, longest=0.362 s, average=0.002 s; distance=4239 kB, estimate=4239 kB
db-1   | 2025-08-19 06:38:10.788 UTC [47] LOG:  database system is shut down
db-1   |  done
db-1   | server stopped
db-1   |
db-1   | PostgreSQL init process complete; ready for start up.
db-1   |
db-1   | 2025-08-19 06:38:10.937 UTC [1] LOG:  starting PostgreSQL 15.14 (Debian 15.14-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
db-1   | 2025-08-19 06:38:10.940 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1   | 2025-08-19 06:38:10.941 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1   | 2025-08-19 06:38:11.005 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
web-1 exited with code 1
db-1   | 2025-08-19 06:38:11.057 UTC [63] LOG:  database system was shut down at 2025-08-19 06:38:10 UTC
db-1   | 2025-08-19 06:38:11.076 UTC [1] LOG:  database system is ready to accept connections
  Gracefully stopping... (press Ctrl+C again to force)
[+] Stopping 2/2
 ✔ Container dashboard-web-1  Stopped                                                          0.0s
 ✔ Container dashboard-db-1   Stopped                                                          0.8s
canceled
root@vps3130894:/var/dashboard# nano ./app/core/config.py
root@vps3130894:/var/dashboard# apt update
Hit:1 http://security.debian.org/debian-security trixie-security InRelease
Hit:2 https://deb.debian.org/debian trixie InRelease
Hit:3 https://deb.debian.org/debian trixie-updates InRelease
All packages are up to date.
root@vps3130894:/var/dashboard# ./venv.sh
-bash: ./venv.sh: Permission denied
root@vps3130894:/var/dashboard# bash ./venv.sh
WARN[0000] /var/dashboard/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Building 11.1s (10/10) FINISHED                                                  docker:default
 => [web internal] load build definition from Dockerfile                                       0.0s
 => => transferring dockerfile: 177B                                                           0.0s
 => [web internal] load metadata for docker.io/library/python:3.11-slim                        0.3s
 => [web internal] load .dockerignore                                                          0.1s
 => => transferring context: 2B                                                                0.0s
 => [web 1/5] FROM docker.io/library/python:3.11-slim@sha256:1d6131b5d479888b43200645e03a7844  0.0s
 => [web internal] load build context                                                          0.5s
 => => transferring context: 485.20kB                                                          0.5s
 => CACHED [web 2/5] WORKDIR /app                                                              0.0s
 => CACHED [web 3/5] COPY requirements.txt .                                                   0.0s
 => CACHED [web 4/5] RUN pip install --no-cache-dir -r requirements.txt                        0.0s
 => [web 5/5] COPY . .                                                                         8.0s
 => [web] exporting to image                                                                   1.5s
 => => exporting layers                                                                        1.3s
 => => writing image sha256:e9686ba98c09048c6b73630593767d0f5805bee49d4ec25cdc0c81572e7237e7   0.0s
 => => naming to docker.io/library/dashboard-web                                               0.0s
WARN[0000] /var/dashboard/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 1/2
 ✔ Container dashboard-db-1   Created                                                          0.0s
 ⠙ Container dashboard-web-1  Recreated                                                        1.2s
Attaching to db-1, web-1
db-1   |
db-1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
db-1   |
db-1   | 2025-08-19 06:39:52.405 UTC [1] LOG:  starting PostgreSQL 15.14 (Debian 15.14-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
db-1   | 2025-08-19 06:39:52.406 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1   | 2025-08-19 06:39:52.406 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1   | 2025-08-19 06:39:52.448 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1   | 2025-08-19 06:39:52.512 UTC [28] LOG:  database system was shut down at 2025-08-19 06:38:41 UTC
db-1   | 2025-08-19 06:39:52.547 UTC [1] LOG:  database system is ready to accept connections
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/local/bin/uvicorn", line 8, in <module>
web-1  |     sys.exit(main())
web-1  |              ^^^^^^
web-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
web-1  |     return self.main(*args, **kwargs)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1363, in main
web-1  |     rv = self.invoke(ctx)
web-1  |          ^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
web-1  |     return ctx.invoke(self.callback, **ctx.params)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 794, in invoke
web-1  |     return callback(*args, **kwargs)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 413, in main
web-1  |     run(
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 580, in run
web-1  |     server.run()
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 67, in run
web-1  |     return asyncio.run(self.serve(sockets=sockets))
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
web-1  |     return runner.run(main)
web-1  |            ^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
web-1  |     return self._loop.run_until_complete(task)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 71, in serve
web-1  |     await self._serve(sockets)
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 78, in _serve
web-1  |     config.load()
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 436, in load
web-1  |     self.loaded_app = import_from_string(self.app)
web-1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
web-1  |     module = importlib.import_module(module_str)
web-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
web-1  |     return _bootstrap._gcd_import(name[level:], package, level)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
web-1  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
web-1  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
web-1  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
web-1  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
web-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
web-1  |   File "/app/app/main.py", line 2, in <module>
web-1  |     from app.api.routes import auth, user
web-1  |   File "/app/app/api/routes/auth.py", line 10, in <module>
web-1  |     @router.post("/signup", response_model=schemas.UserOut)
web-1  |                                            ^^^^^^^^^^^^^^^
web-1  | AttributeError: module 'app.schemas' has no attribute 'UserOut'
web-1 exited with code 1